name: Build Executables

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: win
            ext: .exe
          - os: macos-latest
            target: macos
            ext: ''

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build SEA executable
        run: npm run build:sea

      - name: Upload artifacts
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: migrate-blg-gfm-${{ matrix.target }}
          path: build/migrate-blg-gfm-${{ matrix.target }}${{ matrix.ext }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: migrate-blg-gfm-win
          path: ./artifacts

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: migrate-blg-gfm-macos
          path: ./artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./artifacts/migrate-blg-gfm-win.exe
            ./artifacts/migrate-blg-gfm-macos
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
